apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: okfvotg3h-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: okfvotg3h-python 
  name: okfvotg3h-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: okfvotg3h-python 
